fo = open("spades.txt", 'w')
print(fo.name)
print(fo.mode)
print(fo.closed)
fo.write("Hello! This is my first program in file handling")
fo.close()
fo.open("spades.txt", 'a')
fo.write("I'm trying to make is correctly")
fo.close()
fo = open("spades.txt", 'r+')
str = fo.read()
print(str)
